///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TurkeyCitiesModel {
/*
{
  "id": 107120,
  "name": "Aladağ",
  "state_id": 2212,
  "state_code": "01",
  "state_name": "Adana",
  "country_id": 225,
  "country_code": "TR",
  "country_name": "Turkey",
  "latitude": 37.55854,
  "longitude": 35.40196,
  "location": "POINT(35.40196000 37.55854000)",
  "wikidataid": 911286
} 
*/

  int? id;
  String? name;
  int? stateId;
  String? stateCode;
  String? stateName;
  int? countryId;
  String? countryCode;
  String? countryName;
  double? latitude;
  double? longitude;
  String? location;
  int? wikidataid;

  TurkeyCitiesModel({
    this.id,
    this.name,
    this.stateId,
    this.stateCode,
    this.stateName,
    this.countryId,
    this.countryCode,
    this.countryName,
    this.latitude,
    this.longitude,
    this.location,
    this.wikidataid,
  });
  TurkeyCitiesModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    stateId = json['state_id']?.toInt();
    stateCode = json['state_code']?.toString();
    stateName = json['state_name']?.toString();
    countryId = json['country_id']?.toInt();
    countryCode = json['country_code']?.toString();
    countryName = json['country_name']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    location = json['location']?.toString();
    wikidataid = json['wikidataid']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['state_id'] = stateId;
    data['state_code'] = stateCode;
    data['state_name'] = stateName;
    data['country_id'] = countryId;
    data['country_code'] = countryCode;
    data['country_name'] = countryName;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['location'] = location;
    data['wikidataid'] = wikidataid;
    return data;
  }
}
